// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

public final class JointType {
  private JointType() { }
  public static final byte REVOLUTE = 0;
  public static final byte PRISMATIC = 1;

  public static final String[] names = { "REVOLUTE", "PRISMATIC", };

  public static String name(int e) { return names[e]; }
}

