// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

public final class NodeType {
  private NodeType() { }
  public static final byte BUTTON = 0;
  public static final byte SPRITE = 1;
  public static final byte LAYOUT = 2;
  public static final byte LABEL = 3;
  public static final byte UI_SCROLL_VIEW = 4;
  public static final byte UI_LIST_VIEW = 5;

  public static final String[] names = { "BUTTON", "SPRITE", "LAYOUT", "LABEL", "UI_SCROLL_VIEW", "UI_LIST_VIEW", };

  public static String name(int e) { return names[e]; }
}

