// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Sizef extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Sizef __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float width() { return bb.getFloat(bb_pos + 0); }
  public float height() { return bb.getFloat(bb_pos + 4); }

  public static int createSizef(FlatBufferBuilder builder, float width, float height) {
    builder.prep(4, 8);
    builder.putFloat(height);
    builder.putFloat(width);
    return builder.offset();
  }
}

