// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Sprite extends Table {
  public static Sprite getRootAsSprite(ByteBuffer _bb) { return getRootAsSprite(_bb, new Sprite()); }
  public static Sprite getRootAsSprite(ByteBuffer _bb, Sprite obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Sprite __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String frameName() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer frameNameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }

  public static int createSprite(FlatBufferBuilder builder,
      int frameNameOffset) {
    builder.startObject(1);
    Sprite.addFrameName(builder, frameNameOffset);
    return Sprite.endSprite(builder);
  }

  public static void startSprite(FlatBufferBuilder builder) { builder.startObject(1); }
  public static void addFrameName(FlatBufferBuilder builder, int frameNameOffset) { builder.addOffset(0, frameNameOffset, 0); }
  public static int endSprite(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

