// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Vec4b extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Vec4b __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int a() { return bb.get(bb_pos + 0) & 0xFF; }
  public int r() { return bb.get(bb_pos + 1) & 0xFF; }
  public int g() { return bb.get(bb_pos + 2) & 0xFF; }
  public int b() { return bb.get(bb_pos + 3) & 0xFF; }

  public static int createVec4b(FlatBufferBuilder builder, int a, int r, int g, int b) {
    builder.prep(1, 4);
    builder.putByte((byte)b);
    builder.putByte((byte)g);
    builder.putByte((byte)r);
    builder.putByte((byte)a);
    return builder.offset();
  }
}

