// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Vec4f extends Struct {
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Vec4f __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float a() { return bb.getFloat(bb_pos + 0); }
  public float r() { return bb.getFloat(bb_pos + 4); }
  public float g() { return bb.getFloat(bb_pos + 8); }
  public float b() { return bb.getFloat(bb_pos + 12); }

  public static int createVec4f(FlatBufferBuilder builder, float a, float r, float g, float b) {
    builder.prep(4, 16);
    builder.putFloat(b);
    builder.putFloat(g);
    builder.putFloat(r);
    builder.putFloat(a);
    return builder.offset();
  }
}

