// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

public final class BodyType {
  private BodyType() { }
  public static final byte STATIC = 0;
  public static final byte DYNAMIC = 1;
  public static final byte KINEMATIC = 2;

  public static final String[] names = { "STATIC", "DYNAMIC", "KINEMATIC", };

  public static String name(int e) { return names[e]; }
}

