// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Button extends Table {
  public static Button getRootAsButton(ByteBuffer _bb) { return getRootAsButton(_bb, new Button()); }
  public static Button getRootAsButton(ByteBuffer _bb, Button obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Button __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String text() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String textureNormal() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textureNormalAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public String textureSelected() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textureSelectedAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public String textureDisabled() { int o = __offset(10); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textureDisabledAsByteBuffer() { return __vector_as_bytebuffer(10, 1); }

  public static int createButton(FlatBufferBuilder builder,
      int textOffset,
      int textureNormalOffset,
      int textureSelectedOffset,
      int textureDisabledOffset) {
    builder.startObject(4);
    Button.addTextureDisabled(builder, textureDisabledOffset);
    Button.addTextureSelected(builder, textureSelectedOffset);
    Button.addTextureNormal(builder, textureNormalOffset);
    Button.addText(builder, textOffset);
    return Button.endButton(builder);
  }

  public static void startButton(FlatBufferBuilder builder) { builder.startObject(4); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(0, textOffset, 0); }
  public static void addTextureNormal(FlatBufferBuilder builder, int textureNormalOffset) { builder.addOffset(1, textureNormalOffset, 0); }
  public static void addTextureSelected(FlatBufferBuilder builder, int textureSelectedOffset) { builder.addOffset(2, textureSelectedOffset, 0); }
  public static void addTextureDisabled(FlatBufferBuilder builder, int textureDisabledOffset) { builder.addOffset(3, textureDisabledOffset, 0); }
  public static int endButton(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

