// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

public final class Component {
  private Component() { }
  public static final byte NONE = 0;
  public static final byte Sprite = 1;
  public static final byte Label = 2;
  public static final byte Button = 3;

  public static final String[] names = { "NONE", "Sprite", "Label", "Button", };

  public static String name(int e) { return names[e]; }
}

