// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

public final class FixtureType {
  private FixtureType() { }
  public static final byte POLYGON = 0;
  public static final byte CIRCLE = 1;
  public static final byte LINE = 2;

  public static final String[] names = { "POLYGON", "CIRCLE", "LINE", };

  public static String name(int e) { return names[e]; }
}

