// automatically generated by the FlatBuffers compiler, do not modify

package Editor;

import java.nio.*;
import java.lang.*;

import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class Label extends Table {
  public static Label getRootAsLabel(ByteBuffer _bb) { return getRootAsLabel(_bb, new Label()); }
  public static Label getRootAsLabel(ByteBuffer _bb, Label obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { bb_pos = _i; bb = _bb; }
  public Label __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String font() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fontAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public String text() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer textAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }

  public static int createLabel(FlatBufferBuilder builder,
      int fontOffset,
      int textOffset) {
    builder.startObject(2);
    Label.addText(builder, textOffset);
    Label.addFont(builder, fontOffset);
    return Label.endLabel(builder);
  }

  public static void startLabel(FlatBufferBuilder builder) { builder.startObject(2); }
  public static void addFont(FlatBufferBuilder builder, int fontOffset) { builder.addOffset(0, fontOffset, 0); }
  public static void addText(FlatBufferBuilder builder, int textOffset) { builder.addOffset(1, textOffset, 0); }
  public static int endLabel(FlatBufferBuilder builder) {
    int o = builder.endObject();
    return o;
  }
}

